version: '2'

volumes:
  pgdata:

services:
  postgres:
      restart: always
      image: postgres:11.5
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
      environment:
        - POSTGRES_PASSWORD=secret

  web:
      image: pyarweb
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      links:
        - postgres
      depends_on:
        - postgres
      environment:
        - DB_USER=postgres
        - DB_NAME=postgres
        - DB_PASS=secret
        - DB_SERVICE=postgres
        - DJANGO_SETTINGS_MODULE=pyarweb.settings.development
        # These environment variables must be defined in a .env file or
        # from the shell before starting the containers
        - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
        - TELEGRAM_MODERATORS_CHAT_ID=${TELEGRAM_MODERATORS_CHAT_ID}
        - FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN}
        - FACEBOOK_PAGE_ID=${FACEBOOK_PAGE_ID}
        - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
        - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
        - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
        - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
